ragflow:
  host: 0.0.0.0
  http_port: 9380
mysql:
  name: 'rag_flow'
  user: 'root'
  password: 'root'
  host: '127.0.0.1'
  port: 3306
  max_connections: 100
  stale_timeout: 30
minio:
  user: 'xxx'
  password: 'xxxxx'
  host: '127.0.0.1:6900'
redis:
  db: 4
  password: ''
  host: '127.0.0.1:6379'
es:
  hosts: 'http://127.0.0.1:9200'
user_default_llm:
  factory: 'Tongyi-Qianwen'
  api_key: 'sk-xxxxxxxxxxxxx'
  base_url: ''
oauth:
  github:
    client_id: xxxxxxxxxxxxxxxxxxxxxxxxx
    secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    url: https://github.com/login/oauth/access_token
authentication:
  client:
    switch: false
    http_app_key:
    http_secret_key:
  site:
    switch: false
permission:
  switch: false
  component: false
  dataset: false